#! /bin/bash
echo "меню с запусками редакторов"
echo "
=========================
=                       =
=      MENU             =
=      1 -vim           =
=      2 -nano          =
=      3 -links         =
=      4 -exit          =
========================="

read menu

case $menu in
	1 ) vi;;
	2 ) nano;;
	3 ) links;;
	4 ) exit 0;;
	* ) echo "Вы ввели некорректное значение!";;
esac
done
 
